changed the contribute data ui
coronasafe/life pull request #162
Opened 2021-04-27 14:09 UTC by khavinshankar

issue #150, New UI for the "Contribute Verified Data" page

2021-04-27 14:34 UTC, Deep-Codes commented on pages/data.js
> -            <section className="flex flex-col items-center md:pt-5">
Add padding or anything so that header theme btn & lang selector don't overlap on Mobile Screens

2021-04-27 14:37 UTC, Deep-Codes requested changes
![ss](https://user-images.githubusercontent.com/61158210/116260140-0ec93d80-a794-11eb-96a6-954161346d5d.png)

On Safari Looks like this ....

On Safari Macos

<img width="729" alt="Screenshot 2021-04-27 at 8 06 53 PM" src="https://user-images.githubusercontent.com/61158210/116260217-1e488680-a794-11eb-8b9a-f3dea89d23e5.png">

2021-04-27 14:37 UTC, Deep-Codes commented
@khavinshankar  Is autoprefixer working ?

2021-04-27 14:46 UTC, Deep-Codes commented on pages/data.js
> -            <section className="flex flex-col items-center md:pt-5">
add `pt-10` instead of `md:pt-5`

2021-04-27 15:22 UTC, khavinshankar commented
> @khavinshankar Is autoprefixer working ?

not sure

2021-04-27 17:44 UTC, Deep-Codes commented
@khavinshankar still having the same problem

I would see something from my side. :(

2021-04-28 03:59 UTC, merged

2021-04-28 05:35 UTC, joelsajichacko commented
On Desktop Chrome browser, it look like this
If possible ,please make this look similar to Safari Mac Os. Now the size of card is small and also the change the color of subtext..its too hard to read.

![Screenshot (357)](https://user-images.githubusercontent.com/45791338/116351320-1a0e7e80-a811-11eb-99c7-d75185f61cce.png)